### ISSUE TITLE
我发现在数据库后台新增加的数据 需要我重新启动服务刷新才会出现请问这个和数据库连接有关系么 

### ISSUE THREAD

**Issue by Orange-YXH** [amisadmin/fastapi-user-auth#17]
我使用的是create_async_engine 创建的异步数据库引擎
`
engine = create_async_engine(url='mysql+aiomysql://root:123456@localhost:3306/fastapi')
# 使用`JwtTokenStore`创建auth对象
auth = Auth(
    db=AsyncDatabase(engine),
    token_store=JwtTokenStore(secret_key='1558858285966')
)
# 将auth对象传入AdminSite
site = AuthAdminSite(
    settings=Settings(database_url_async='mysql+aiomysql://root:123456@localhost:3306/fastapi'),
    auth=auth
)`

**Comment by amisadmin** [comment]
将auth的db对象和site的db对象使用同一个, 你这样虽然是相同的数据库连接,但是他会创建两个db对象
