### ISSUE TITLE
ImportError: cannot import name 'schema_create_by_schema' from 'fastapi_amis_admin.crud.utils' 

### ISSUE THREAD

**Issue by EchoShoot** [amisadmin/fastapi-user-auth#19]
Name: fastapi_amis_admin
Version: 0.6.0

Name: fastapi_user_auth
Version: 0.5.0

**Comment by amisadmin** [comment]
fastapi_user_auth 0.5.0  不使用支持 fastapi_amis_admin 0.6.0

**Comment by OlyaLuchko** [comment]
when are you going to upgrade to fastapi_amis_admin 0.6?

**Comment by amisadmin** [comment]
fastapi_user_auth has been fully refactored by me using casbin and supports action level and field level permission control, and I may release it when it is fully mature.

**Comment by MatsiukMykola** [comment]
great news, can you share, please?
casbin - can sample be replaced ?

**Comment by amisadmin** [comment]
> great news, can you share, please? casbin - can sample be replaced ?

It's not available yet, and there are a lot of changes.

**Comment by EchoShoot** [comment]
十分期待!!!
