### ISSUE TITLE
子角色无法添加用户

### ISSUE THREAD

**Issue by zeroChen00** [amisadmin/fastapi-user-auth#49]
使用root添加用户test，并给予用户管理权限（增删改查）
![Snipaste_2024-09-27_15-34-34](https://github.com/user-attachments/assets/9e526c5b-2322-44a2-b10d-afc6d855dd26)

使用test登录，无法添加角色，密码字段消失，添加就会报错
![Snipaste_2024-09-27_15-34-09](https://github.com/user-attachments/assets/02dc62f3-a17f-436a-aa64-da068fd7b9c6)

**Comment by zhangtongxuedecode** [comment]
还需要配置相关的数据权限。

**Comment by zeroChen00** [comment]
> 还需要配置相关的数据权限。

数据权限配置默认是空的。在字段控制那边好像也涉及数据权限，但是代码是pass

**Comment by zeroChen00** [comment]
> 还需要配置相关的数据权限。

数据权限配置默认是空的。在字段控制那边好像也涉及数据权限，但是代码是pass

**Comment by zeroChen00** [comment]
> 还需要配置相关的数据权限。

看到了，用户管理那边确实有数据权限，其他没有。感谢老哥！
