### ISSUE TITLE
admin登录后提示404

### ISSUE THREAD

**Issue by charsxiong** [amisadmin/fastapi-user-auth#52]
如果不添加下面的casbin策略，那么使用admin账号登录后一直提示ERR_TOO_MANY_REDIRECTS，添加策略后，再使用admin账号登录后，就页面提示404，通过F12查看接口返回，也未找到对应的报错接口；
=================
# 创建初始化数据库表
@app.on_event("startup")
async def startup():
    await site.db.async_run_sync(SQLModel.metadata.create_all, is_session=False)
    await auth.create_role_user('root')
    await auth.create_role_user('admin')
    if not auth.enforcer.enforce("u:admin", site.unique_id, "page", "page"):
        await auth.enforcer.add_policy("u:admin", site.unique_id, "page", "page", "allow")

pydantic_settings==2.6.1
pydantic==2.9.2
pydantic==1.10.11
fastapi==0.103.2
fastapi_user_auth==0.7.3
fastapi_amis_admin==0.7.2
aiomysql==0.2.0
uvicorn==0.32.0
starlette=0.27.0

**Comment by charsxiong** [comment]
在重定向问题处理完成后，这个问题自动消失；

**Comment by zfdhlx** [comment]
我遇到了同样的问题，请问重定向是怎么处理的
