### ISSUE TITLE
创建新用户后如何实现admin/guest的ro/rw权限控制

### ISSUE THREAD

**Issue by charsxiong** [amisadmin/fastapi-user-auth#53]
root账号可以正常登录，通过自定义注册模型新增了很多page，后续可能会有很多人访问，想通过账号来控制读写，和访问页面的权限：
1.目前使用fastapi_user_auth默认的账号体系，注册后的新用户想要通过类似管理员(rw),普通用户(rw/ro),游客(ro)这样的权限控制；
2.账号注册后，通过role来自动分配permisson page，不用手工去user authentication中一个个赋权；

pydantic_settings==2.6.1
pydantic==2.9.2
pydantic==1.10.11
fastapi==0.103.2
fastapi_user_auth==0.7.3
fastapi_amis_admin==0.7.2
aiomysql==0.2.0
uvicorn==0.32.0
starlette=0.27.0

**Comment by zeroChen00** [comment]
默认就是新建角色，给角色赋权，新建的用户直接赋值角色就行，不过还是要手动操作

**Comment by charsxiong** [comment]
目前看仍然需要手动给对应的账号赋权，这一块后续考虑用python来实现，问题先关闭，感谢了
